# Generated by Django 5.0.7 on 2024-07-26 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('host_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=30)),
                ('contacte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='addressbook.allcontact')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntel', models.CharField(max_length=10)),
                ('contactp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='addressbook.allcontact')),
            ],
        ),
    ]
