# Generated by Django 5.0.7 on 2024-07-29 18:11

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='file_type',
            field=models.CharField(default='raw', max_length=20),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
