# Generated by Django 5.0.7 on 2024-07-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.CharField(default="my address"),
        ),
    ]
