# Generated by Django 5.0.7 on 2024-07-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='core/media/gus.png', upload_to='profile_images'),
        ),
    ]
